name: CI/CD Docker- Workflow

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Setup Docker Buildx
      - uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t esyasoftshubham/mydockerimage:${{ github.sha }} .
          docker push esyasoftshubham/mydockerimage:${{ github.sha }}

      # Step 5: Update deployment.yaml with new image tag
      - name: Update deployment.yaml
        run: |
          sed -i "s|image: esyasoftshubham/mydockerimage:.*|image: esyasoftshubham/mydockerimage:${{ github.sha }}|" deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deployment.yaml
          git commit -m "Update deployment image to ${{ github.sha }}" || echo "No changes to commit"
          git push || echo "Push failed (likely no changes)"

      # Step 6: Setup kubectl with kubeconfig
      - name: Setup kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # Step 7: ploy to Kernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/flask-deployment flask-container=esyasoftshubham/mydockerimage:${{ github.sha }} --record
          kubectl rollout status deployment/flask-deployment

      # Step 8: eployment
      - name: Verify deployment
        run: kubectl get pods -o wide
